### ISSUE TITLE
Getting Error Message

### ISSUE THREAD

**Issue by muhamsid** [lewoudar/ib_client#1]
I am getting below error while using in Python3. I have install through `pip3 install ib-client`

```
$ pip3 install ib-client
Collecting ib-client
  Using cached https://files.pythonhosted.org/packages/c8/db/1973e6da470be44a4614a3ea38bb18750a01469ed05eb0e406f66fe4606e/ib_client-0.1.2-py3-none-any.whl
Collecting requests (from ib-client)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 314kB/s 
Collecting click (from ib-client)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting click-didyoumean (from ib-client)
Collecting python-dotenv (from ib-client)
  Using cached https://files.pythonhosted.org/packages/57/c8/5b14d5cffe7bb06bedf9d66c4562bf90330d3d35e7f0266928c370d9dd6d/python_dotenv-0.10.3-py2.py3-none-any.whl
Collecting click-completion (from ib-client)
Collecting pygments (from ib-client)
  Downloading https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl (883kB)
     |████████████████████████████████| 890kB 754kB/s 
Collecting idna<2.9,>=2.5 (from requests->ib-client)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 11.9MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->ib-client)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
     |████████████████████████████████| 143kB 1.6MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->ib-client)
  Downloading https://files.pythonhosted.org/packages/91/0d/7777358f672a14b7ae0dfcd29f949f409f913e0578190d6bfa68eb55864b/urllib3-1.25.4-py2.py3-none-any.whl (125kB)
     |████████████████████████████████| 133kB 2.2MB/s 
Collecting certifi>=2017.4.17 (from requests->ib-client)
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
     |████████████████████████████████| 163kB 2.0MB/s 
Collecting six (from click-completion->ib-client)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting shellingham (from click-completion->ib-client)
  Using cached https://files.pythonhosted.org/packages/2d/ac/e8a34d4b3d24bf554f40651b2aac549a3fc7223725bf10fbdfe2083b6372/shellingham-1.3.1-py2.py3-none-any.whl
Collecting jinja2 (from click-completion->ib-client)
  Downloading https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl (124kB)
     |████████████████████████████████| 133kB 1.8MB/s 
Collecting MarkupSafe>=0.23 (from jinja2->click-completion->ib-client)
  Downloading https://files.pythonhosted.org/packages/ce/c6/f000f1af136ef74e4a95e33785921c73595c5390403f102e9b231b065b7a/MarkupSafe-1.1.1-cp37-cp37m-macosx_10_6_intel.whl
Installing collected packages: idna, chardet, urllib3, certifi, requests, click, click-didyoumean, python-dotenv, six, shellingham, MarkupSafe, jinja2, click-completion, pygments, ib-client
Successfully installed MarkupSafe-1.1.1 certifi-2019.9.11 chardet-3.0.4 click-7.0 click-completion-0.5.1 click-didyoumean-0.0.3 ib-client-0.1.2 idna-2.8 jinja2-2.10.1 pygments-2.4.2 python-dotenv-0.10.3 requests-2.22.0 shellingham-1.3.1 six-1.12.0 urllib3-1.25.4
```

```
$ python3
Python 3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import infoblox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/msiddique/Desktop/_Code_/pwc/infoblox/infoblox-wapi/lib/python3.7/site-packages/infoblox/__init__.py", line 10, in <module>
    from .scripts.utils import pretty_echo, handle_json_arguments, parse_dict_items, handle_json_file
ModuleNotFoundError: No module named 'infoblox.scripts'
```

**Comment by lewoudar** [comment]
Hi @muhamsid , thank you for this bug report, I think there is an issue with my way to find packages in `setup.py` I will check it soon

**Comment by lewoudar** [comment]
The problem should be fixed now. If it is not the case for you, feel free to add comments.
